# Generated by Django 4.2.2 on 2023-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('tagline', models.CharField(max_length=200)),
                ('schedule', models.DateTimeField()),
                ('description', models.TextField()),
                ('moderator', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('rigor_rank', models.IntegerField()),
            ],
        ),
    ]
